### ISSUE TITLE
Use protocol-relative url

### ISSUE THREAD

**Issue by suzhouxing** [streetturtle/jekyll-cv-crafter#1]
Please use //url to replace http://url in index.html.
Since modern browsers may block the http request if the original url is opened with SSL.

References:
https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by streetturtle** [comment]
Hi!

Thanks for your comment, good spot! I've replaced links to `http` by `https`. I believe this way it's more clear.
Please let me know in case of any questions.

Thanks again!
