### ISSUE TITLE
Not able to integrate into site

### ISSUE THREAD

**Issue by Alwurts** [streetturtle/jekyll-cv-crafter#5]
Hi I want to integrate this crafter content into my jekyll website which is currently using a minimal-mistakes theme. I followed your instructions as per below:
 
So only thing you need to do is to fill the cv.yml. As I mentioned above you can easily integrate this CV in your blog (if it's hosted on github pages) by putting cv.yml in _data folder of your blog, cv.scss in css folder of your blog and renaming index.html to cv.html.

My cv.html is located at the root of my site, and when building in jekyll local serve i'm able to access it but the formatting is not correct, i get the error.

[2018-08-01 03:18:32] ERROR `/cv/assets/cv.css' not found.
[2018-08-01 03:18:32] ERROR `/cv/assets/font-awesome/css/font-awesome.min.css' not found.

I Checked for the files being there but for some reason is not able to find the cv.css.

Is this something you can maybe help with?

**Comment by streetturtle** [comment]
Can you push your changes to github? It would be easier to check what is wrong.

**Comment by Alwurts** [comment]
I pushed the changes to my alejandrowurts repo in GitHub; I'm using everything as I downloaded from your repo.

You can see the output at http://alejandrowurts.com/cv/ where it doesn't load correctly.

Thank you for your help, hopefully this is something I can implement.

**Comment by streetturtle** [comment]
I created a [pull request](https://github.com/Alwurts/alejandrowurts/pull/1). You will need to add font-awesome folder to your asset to have icons, I missed it in docs.

**Comment by streetturtle** [comment]
Did it help? Can I close this issue?

**Comment by Alwurts** [comment]
Yes it was the link to the folder that was giving trouble, all fixed now
Thanks
